# Generated by Django 2.2.13 on 2020-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200629_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
