# Generated by Django 2.2.13 on 2020-06-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="jbvmhjmmjgvjhv",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
