# Generated by Django 2.2.13 on 2020-06-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_jbvmhjmmjgvjhv"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="jbvmhjmmjgvjhv",),
    ]
